#!/usr/bin/env python3
"""
Podcast Show-Notes Generator — enhances podcast-ad-cleaner output.
Takes the VTT transcript and generates formatted shownotes.

Usage:
  python3 generate_shownotes.py --vtt transcript.vtt [--chapters chapters.json] [--output shownotes.md]
"""

import argparse
import json
import os
import re
from pathlib import Path


def parse_vtt(vtt_path: str) -> list:
    """Parse a VTT file into time-stamped text blocks."""
    with open(vtt_path) as f:
        content = f.read()
    blocks = re.findall(
        r"(\d{2}:\d{2}:\d{2}\.\d{3}) --> (\d{2}:\d{2}:\d{2}\.\d{3})\n(.+?)(?=\n\n|\Z)",
        content,
        re.DOTALL,
    )
    return [
        {"start": s, "end": e, "text": t.strip().replace("\n", " ")}
        for s, e, t in blocks
    ]


def load_chapters(chapters_path: str) -> list:
    """Load chapter markers from JSON."""
    if not chapters_path or not os.path.exists(chapters_path):
        return []
    with open(chapters_path) as f:
        data = json.load(f)
    return data.get("chapters", [])


def format_timestamp(ts: str) -> str:
    """Convert VTT timestamp to short format (MM:SS)."""
    parts = ts.replace(",", ".").split(":")
    if len(parts) == 3:
        h, m, s = parts
        return f"{int(h):d}:{m}:{s.split('.')[0]}"
    return ts


def main():
    parser = argparse.ArgumentParser(description="Podcast Show-Notes Generator")
    parser.add_argument("--vtt", required=True, help="VTT transcript file")
    parser.add_argument("--chapters", help="JSON chapters file (optional)")
    parser.add_argument("--output", "-o", default="shownotes.md", help="Output path")
    args = parser.parse_args()

    blocks = parse_vtt(args.vtt)
    chapters = load_chapters(args.chapters)

    total_duration = blocks[-1]["end"] if blocks else "00:00:00.000"
    word_count = sum(len(b["text"].split()) for b in blocks)

    output = "# Podcast Show-Notes\n\n"
    output += f"- **Duration**: {total_duration}\n"
    output += f"- **Words**: {word_count}\n"
    output += f"- **Transcript Source**: `{args.vtt}`\n\n"

    if chapters:
        output += "## Chapters\n\n"
        output += "| Time | Title |\n|------|-------|\n"
        for ch in chapters:
            t = format_timestamp(ch.get("startTime", "0"))
            output += f"| `{t}` | {ch.get('title', 'Untitled')} |\n"
        output += "\n"

    output += "## Timeline\n\n"
    for b in blocks[:30]:
        t = format_timestamp(b["start"])
        text = b["text"][:80].replace("\n", " ")
        output += f"- `{t}` {text}...\n"

    output += "\n---\n*Generated by Media Pipeline*\n"

    with open(args.output, "w") as f:
        f.write(output)
    print(f"Show-Notes saved to: {args.output}", flush=True)


if __name__ == "__main__":
    main()
